basePath: /api/v1
host: localhost:5000
info:
  contact:
    name: Gary Greene
    url: https://github.com/greeneg/update-reporterd
  description: An API for Reporting Software Updates
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Update Reporter Daemon
  version: 0.0.1
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
